#include "User.h"
#include <ctime>

User::User() : 
    username(""), 
    passwordHash(""), 
    fullName(""), 
    email(""),
    phoneNumber(""),
    role(REGULAR),
    isAutoGeneratedPassword(false),
    isFirstLogin(true),
    creationDate(time(NULL)),
    lastLoginDate(0) {}

User::User(const std::string& username, 
          const std::string& passwordHash, 
          const std::string& fullName,
          const std::string& email,
          const std::string& phoneNumber,
          UserRole role) :
    username(username),
    passwordHash(passwordHash),
    fullName(fullName),
    email(email),
    phoneNumber(phoneNumber),
    role(role),
    isAutoGeneratedPassword(false),
    isFirstLogin(true),
    creationDate(time(NULL)),
    lastLoginDate(0) {}

std::string User::getUsername() const {
    return username;
}

std::string User::getPasswordHash() const {
    return passwordHash;
}

std::string User::getFullName() const {
    return fullName;
}

std::string User::getEmail() const {
    return email;
}

std::string User::getPhoneNumber() const {
    return phoneNumber;
}

UserRole User::getRole() const {
    return role;
}

bool User::getIsAutoGeneratedPassword() const {
    return isAutoGeneratedPassword;
}

bool User::getIsFirstLogin() const {
    return isFirstLogin;
}

time_t User::getCreationDate() const {
    return creationDate;
}

time_t User::getLastLoginDate() const {
    return lastLoginDate;
}

void User::setFullName(const std::string& fullName) {
    this->fullName = fullName;
}

void User::setEmail(const std::string& email) {
    this->email = email;
}

void User::setPhoneNumber(const std::string& phoneNumber) {
    this->phoneNumber = phoneNumber;
}

void User::setPasswordHash(const std::string& passwordHash) {
    this->passwordHash = passwordHash;
}

void User::setIsAutoGeneratedPassword(bool isAuto) {
    this->isAutoGeneratedPassword = isAuto;
}

void User::setIsFirstLogin(bool isFirst) {
    this->isFirstLogin = isFirst;
}

void User::setLastLoginDate(time_t date) {
    this->lastLoginDate = date;
}

bool User::isAdmin() const {
    return role == ADMIN;
} 
